### ISSUE TITLE
didReceiveScriptMessage中怎么返回值给js

### ISSUE THREAD

**Issue by czl0325** [domanc/HYBridWKWebView-MessageHandler#1]

**Comment by czl0325** [comment]
didReceiveScriptMessage中想返回值给js，除了使用evaluateJavaScript执行js的方法外，有没有直接返回的方法？

**Comment by domanc** [comment]
没有,互调的话js只能通过evaluateJavaScript.

**Comment by domanc** [comment]
> didReceiveScriptMessage中想返回值给js，除了使用evaluateJavaScript执行js的方法外，有没有直接返回的方法？

没有,互调的话js只能通过evaluateJavaScript.你可以看看其他框架,最后都是通过evaluateJavaScript或者stringByEvaluatingJavaScriptFromString来完成.
